data:
  data_dir: /Users/pooya/Documents/SFU/Courses/CMPT985/Project/MGNData # Training data directory
  split_file: /Users/pooya/Documents/SFU/Courses/CMPT985/Project/MGNData/split_file.npz
experiment:
  root_dir: /Users/pooya/Documents/SFU/Courses/CMPT985/Project/Checkpoints # Where to save checkpoints and final trained models
  exp_name: trial_1 # exp_name
model:
  spatial_feat: 171
  occ_net: #not used anywhere
    shg:
      n_stacks: 1 #ask
      n_modules: 3 #ask
      in_channels: 3
      out_channels: 256
      depth: 1 #ask
      n_joints: 10 #ask
    mlp:
      channels: [427, 1024, 512, 256, 128]
      no_residual: true  #just dummy
      last_activation: sigmoid   #just dummy
      nlast_activation: relu  #just dummy
      norm: weight #what is this??
  normal_net: #not used anywhere
    unet:
      in_channels: 3
      out_channels: 64
    mlp:
      channels: [491, 1024, 512, 256, 128]
      no_residual: true  #just dummy
      last_activation: sigmoid   #just dummy
      nlast_activation: relu  #just dummy
      norm: weight #what is this??
  color_net: #not used anywhere
    unet:
      in_channels: 3
      out_channels: 64
    mlp:
      channels: [555, 1024, 512, 256, 128]
      no_residual: true  #just dummy
      last_activation: sigmoid   #just dummy
      nlast_activation: relu  #just dummy
      norm: weight #what is this??
renderer:
  renderer_type: simple
  cam_type: orthographic
  im_size: 512
  comp_type: alpha
  radius: 0.003
  points_per_pixel: 10
shg:
  n_stacks: 1 #ask
  n_modules: 3 #ask
  in_channels: 3
  out_channels: 256
  depth: 1 #ask
  n_joints: 10 #ask
unet:
  in_channels: 3
  out_channels: 64
mlp:
  channels: [1024, 512, 256, 128]
  no_residual: true  #just dummy
  last_activation: sigmoid   #just dummy
  nlast_activation: relu  #just dummy
  norm: weight #what is this??
  in_channels: 427
training:
  batch_size: 4
  continue_train: true
  optimizer: Adam
  eval: false
  num_worker: 30
  max_epoch: 100
leap_path: /u/gtiwari/Body_Models/LEAP/smplh/sample_body.pt
body_model_path: /u/gtiwari/Body_Models/smplh
