data:
  data_dir: C:\Users\17788\CMPT985\Multi-Garment_dataset
  split_file: C:\Users\17788\CMPT985\Multi-Garment_dataset/split_file.npz
experiment:
  root_dir: C:\Users\17788\CMPT985\Checkpoints
  exp_name: trial_1 
model:
  spatial_feat: 171
  occ_net:
    shg:
      n_stacks: 1
      n_modules: 3
      in_channels: 3
      out_channels: 256
      depth: 1
      n_joints: 10
    mlp:
      channels: [427, 1024, 512, 256, 128, 1]
      no_residual: true  
      last_activation: sigmoid
      nlast_activation: relu 
      norm:
  normal_net:
    unet:
      in_channels: 3
      out_channels: 64
    mlp:
      channels: [491, 1024, 512, 256, 128, 3]
      no_residual: true  
      last_activation: sigmoid
      nlast_activation: relu
      norm: weight
  color_net:
    unet:
      in_channels: 3
      out_channels: 64
    mlp:
      channels: [555, 1024, 512, 256, 128, 3]
      no_residual: true 
      last_activation: sigmoid
      nlast_activation: relu
      norm: weight
renderer:
  renderer_type: simple
  cam_type: orthographic
  im_size: 512
  comp_type: alpha
  radius: 0.003
  points_per_pixel: 10
shg:
  n_stacks: 1
  n_modules: 3
  in_channels: 3
  out_channels: 256
  depth: 1
  n_joints: 10
unet:
  in_channels: 3
  out_channels: 64
mlp:
  channels: [1024, 512, 256, 128]
  no_residual: true
  last_activation: sigmoid 
  nlast_activation: relu
  norm: weight
  in_channels: 427
training:
  batch_size: 1
  continue_train: false
  optimizer: Adam
  eval: false
  num_worker: 0
  max_epoch: 100
leap_path: C:\Users\17788\CMPT985\body_models\leap\smplh\sample_body.pt
body_model_path: C:\Users\17788\CMPT985\body_models\smplh
